# Generated by Django 5.2.17 on 2026-08-09 22:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='catalog.producto')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='inventory_cantidad_disponible_gte_0')],
            },
        ),
    ]
