# Generated by Django 5.2.17 on 2026-08-16 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO_MERCADERIA', 'Ingreso de mercadería'), ('VENTA_PEDIDO', 'Venta por pedido'), ('VENTA_PRESENCIAL', 'Venta presencial'), ('CANCELACION_PEDIDO', 'Cancelación de pedido'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observacion', models.TextField(blank=True, default='')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.inventario')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='inventory_movimiento_cantidad_gt_0'), models.CheckConstraint(condition=models.Q(('tipo_movimiento__in', ['INGRESO_MERCADERIA', 'VENTA_PEDIDO', 'VENTA_PRESENCIAL', 'CANCELACION_PEDIDO', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO'])), name='inventory_movimiento_tipo_valido')],
            },
        ),
    ]
