# Generated by Django 5.2.17 on 2026-08-28 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def validar_movimientos_reservados_sin_pedido(apps, schema_editor):
    MovimientoInventario = apps.get_model(
        "inventory", "MovimientoInventario"
    )
    ids = list(
        MovimientoInventario.objects.filter(
            tipo_movimiento__in=("VENTA_PEDIDO", "CANCELACION_PEDIDO")
        )
        .order_by("pk")
        .values_list("pk", flat=True)
    )
    if ids:
        raise RuntimeError(
            "No puede vincularse el historial reservado a Pedidos. "
            f"Movimientos incompatibles: {ids}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientoinventario'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            validar_movimientos_reservados_sin_pedido,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='orders.pedido'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_disponible',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pedido__isnull', False), ('tipo_movimiento__in', ('VENTA_PEDIDO', 'CANCELACION_PEDIDO'))), models.Q(('pedido__isnull', True), ('tipo_movimiento__in', ('INGRESO_MERCADERIA', 'VENTA_PRESENCIAL', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO'))), _connector='OR'), name='inventory_movimiento_pedido_coherente'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('pedido__isnull', False), ('tipo_movimiento__in', ('VENTA_PEDIDO', 'CANCELACION_PEDIDO'))), fields=('pedido', 'inventario', 'tipo_movimiento'), name='inventory_mov_pedido_inv_tipo_uniq'),
        ),
    ]
