# Generated by Django 5.2.17 on 2026-08-09 22:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('peso', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_desde_3', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_desde_20', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nombre', 'peso'), name='catalog_producto_nombre_peso_uniq'), models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='catalog_producto_precio_unitario_gt_0'), models.CheckConstraint(condition=models.Q(('precio_desde_3__gt', 0)), name='catalog_producto_precio_desde_3_gt_0'), models.CheckConstraint(condition=models.Q(('precio_desde_20__gt', 0)), name='catalog_producto_precio_desde_20_gt_0')],
            },
        ),
    ]
