# Generated by Django 5.2.17 on 2026-08-17 05:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('session_key', ''), _negated=True), name='cart_carrito_session_key_no_vacia')],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_desde_3_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_desde_20_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carrito', to='catalog.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carrito', 'producto'), name='cart_item_carrito_producto_uniq'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cart_item_cantidad_gt_0'), models.CheckConstraint(condition=models.Q(('precio_unitario_snapshot__gt', 0)), name='cart_item_precio_unitario_gt_0'), models.CheckConstraint(condition=models.Q(('precio_desde_3_snapshot__gt', 0)), name='cart_item_precio_desde_3_gt_0'), models.CheckConstraint(condition=models.Q(('precio_desde_20_snapshot__gt', 0)), name='cart_item_precio_desde_20_gt_0')],
            },
        ),
    ]
