# Generated by Django 5.2.17 on 2026-08-28 19:42

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_token_checkout'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=32)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dni',), name='orders_cliente_dni_uniq'), models.CheckConstraint(condition=models.Q(('dni__regex', '^[0-9]{6,8}$')), name='orders_cliente_dni_formato'), models.CheckConstraint(condition=models.Q(('nombre__regex', '.*\\S.*')), name='orders_cliente_nombre_no_vacio'), models.CheckConstraint(condition=models.Q(('apellido__regex', '.*\\S.*')), name='orders_cliente_apellido_no_vacio'), models.CheckConstraint(condition=models.Q(('telefono__regex', '.*[0-9].*')), name='orders_cliente_telefono_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=15)),
                ('token_idempotencia', models.UUIDField(editable=False)),
                ('huella_sesion_origen', models.CharField(editable=False, max_length=64)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', editable=False, max_length=10)),
                ('modalidad_entrega', models.CharField(choices=[('RETIRO', 'Retiro'), ('ENVIO_DOMICILIO', 'Envío a domicilio')], editable=False, max_length=20)),
                ('observaciones', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('cantidad_total', models.PositiveBigIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('importe_total', models.DecimalField(decimal_places=2, editable=False, max_digits=31, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('nombre_cliente', models.CharField(editable=False, max_length=150)),
                ('apellido_cliente', models.CharField(editable=False, max_length=150)),
                ('dni_cliente', models.CharField(editable=False, max_length=20)),
                ('telefono_cliente', models.CharField(editable=False, max_length=32)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='orders.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(editable=False, max_length=200)),
                ('numero', models.CharField(editable=False, max_length=30)),
                ('piso', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('departamento', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('localidad', models.CharField(editable=False, max_length=120)),
                ('provincia', models.CharField(editable=False, max_length=120)),
                ('codigo_postal', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('referencias', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='direccion_envio', to='orders.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.TextField(editable=False)),
                ('peso_producto', models.TextField(editable=False)),
                ('cantidad', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_aplicado', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalog.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='orders.pedido')),
            ],
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-fecha_hora_creacion'], name='orders_pedido_estado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('numero_pedido',), name='orders_pedido_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('token_idempotencia',), name='orders_pedido_token_idempotencia_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('numero_pedido__regex', '^YC-[0-9A-HJKMNP-TV-Z]{12}$')), name='orders_pedido_numero_formato'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('huella_sesion_origen__regex', '^[0-9a-f]{64}$')), name='orders_pedido_huella_formato'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENTREGADO', 'CANCELADO'])), name='orders_pedido_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('modalidad_entrega__in', ['RETIRO', 'ENVIO_DOMICILIO'])), name='orders_pedido_modalidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_total__gt', 0)), name='orders_pedido_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('importe_total__gt', 0)), name='orders_pedido_importe_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_cliente__regex', '.*\\S.*')), name='orders_pedido_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('apellido_cliente__regex', '.*\\S.*')), name='orders_pedido_apellido_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('dni_cliente__regex', '^[0-9]{6,8}$')), name='orders_pedido_dni_formato'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('telefono_cliente__regex', '.*[0-9].*')), name='orders_pedido_telefono_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='direccionenvio',
            constraint=models.CheckConstraint(condition=models.Q(('calle__regex', '.*\\S.*')), name='orders_direccion_calle_no_vacia'),
        ),
        migrations.AddConstraint(
            model_name='direccionenvio',
            constraint=models.CheckConstraint(condition=models.Q(('numero__regex', '.*\\S.*')), name='orders_direccion_numero_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='direccionenvio',
            constraint=models.CheckConstraint(condition=models.Q(('localidad__regex', '.*\\S.*')), name='orders_direccion_localidad_no_vacia'),
        ),
        migrations.AddConstraint(
            model_name='direccionenvio',
            constraint=models.CheckConstraint(condition=models.Q(('provincia__regex', '.*\\S.*')), name='orders_direccion_provincia_no_vacia'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='orders_detalle_pedido_producto_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='orders_detalle_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario_aplicado__gt', 0)), name='orders_detalle_precio_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gt', 0)), name='orders_detalle_subtotal_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_producto', ''), _negated=True), name='orders_detalle_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('peso_producto', ''), _negated=True), name='orders_detalle_peso_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.expressions.CombinedExpression(models.F('cantidad'), '*', models.F('precio_unitario_aplicado')))), name='orders_detalle_subtotal_coherente'),
        ),
    ]
